spring:
  application:
    name: leetcode-mcp-server
  main:
    web-application-type: none
    banner-mode: off
  ai:
    mcp:
      server:
        name: leetcode-mcp-server
        version: 0.1.0

leetcode:
  username: prashuchaudhry

logging:
  level:
    root: WARN