spring:
  application:
    name: leetcode-mcp-server
  main:
    web-application-type: none
    banner-mode: off
  ai:
    mcp:
      server:
        name: leetcode-mcp-server
        version: 0.1.0
        stdio: true

logging:
#  pattern:
#    console: ""
  level:
    root: WARN
  file:
    name: /tmp/leetcode-mcp.log